"""Regenerate every FastAutomate icon from branding/fa_mark.svg.
MARK_ADAPTIVE / MARK_TILE set how much of the icon the mark fills (smaller = more padding)."""
import glob
import subprocess
from pathlib import Path

from PIL import Image

MARK_ADAPTIVE = 44  # of the 108dp adaptive canvas (safe zone is 66dp)
MARK_TILE = 0.50  # of legacy square/round icons and the in-app logo.png

ROOT = Path(__file__).resolve().parents[1]
RES = ROOT / "app/src/main/res"
path = (ROOT / "branding/fa_mark.path").read_text()
subprocess.run(["rsvg-convert", "-w", "1024", "-h", "1024", ROOT / "branding/fa_mark.svg", "-o", "/tmp/fa_mark_1024.png"], check=True)
x0, y0, x1, y1 = Image.open("/tmp/fa_mark_1024.png").split()[-1].getbbox()
w, h, cx, cy = x1 - x0, y1 - y0, (x0 + x1) / 2, (y0 + y1) / 2


def vector(viewport, mark_size, fill, note):
    s = mark_size / max(w, h)
    tx, ty = viewport / 2 - cx * s, viewport / 2 - cy * s
    return f'''<?xml version="1.0" encoding="utf-8"?>
<!-- {note}: FastAutomate mark (generated by branding/make_icons.py from branding/fa_mark.svg). -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{viewport}dp"
    android:height="{viewport}dp"
    android:viewportWidth="{viewport}"
    android:viewportHeight="{viewport}">
    <group android:translateX="{tx:.3f}" android:translateY="{ty:.3f}" android:scaleX="{s:.5f}" android:scaleY="{s:.5f}">
        <path android:fillColor="{fill}" android:fillType="evenOdd" android:pathData="{path}"/>
    </group>
</vector>
'''


def tile(size, circle=False):
    k = 1024 * MARK_TILE / max(w, h)
    shape = '<circle cx="512" cy="512" r="512" fill="#fff"/>' if circle else '<rect width="1024" height="1024" rx="225" fill="#fff"/>'
    svg = (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024">{shape}'
           f'<g transform="translate({512 - cx * k:.2f},{512 - cy * k:.2f}) scale({k:.5f})">'
           f'<path fill="#111713" fill-rule="evenodd" d="{path}"/></g></svg>')
    Path("/tmp/fa_tile.svg").write_text(svg)
    subprocess.run(["rsvg-convert", "-w", str(size), "-h", str(size), "/tmp/fa_tile.svg", "-o", "/tmp/fa_tile.png"], check=True)
    return Image.open("/tmp/fa_tile.png").convert("RGBA")


(RES / "drawable/ic_launcher_foreground_fa.xml").write_text(vector(108, MARK_ADAPTIVE, "#FF111713", "launcher foreground"))
(RES / "drawable/mobilerun_logo_square.xml").write_text(vector(293, 250, "@color/icon_default", "in-app logo, theme-aware fill"))
for d, px in {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}.items():
    tile(px).save(RES / f"mipmap-{d}/ic_launcher.webp", "WEBP", lossless=True)
    tile(px, circle=True).save(RES / f"mipmap-{d}/ic_launcher_round.webp", "WEBP", lossless=True)
tile(512).save(RES / "drawable/logo.png")
tile(512).save(ROOT / "branding/fa_app_icon_512.png")
# preview: how a launcher shows the adaptive icon (white circle mask)
k = 108
subprocess.run(["rsvg-convert", "-w", "432", "-h", "432", "-b", "white", "/dev/stdin", "-o", str(ROOT / "branding/preview_adaptive.png")],
               input=(f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 108 108"><circle cx="54" cy="54" r="54" fill="#fff" stroke="#ccc" stroke-width="0.5"/>'
                      f'<g transform="translate({54 - cx * MARK_ADAPTIVE / max(w, h):.3f},{54 - cy * MARK_ADAPTIVE / max(w, h):.3f}) scale({MARK_ADAPTIVE / max(w, h):.5f})">'
                      f'<path fill="#111713" fill-rule="evenodd" d="{path}"/></g></svg>').encode(), check=True)
print("icons regenerated", MARK_ADAPTIVE, MARK_TILE)
